// import Icons
import "bootstrap-icons/font/bootstrap-icons.json";

// import bootstrap
import "bootstrap/dist/css/bootstrap.css";

// import aos css
import "aos/dist/aos.css";

import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import Header from "@/components/header/header";

import "./variables.css";
import "./globals.css";

const ebGaramond = EB_Garamond({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digital News App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ebGaramond.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
